apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: nextcloud-mariadb
  name: nextcloud-mariadb
spec:
  type: ClusterIP
  ports:
  - name: "mariadb"
    port: 3306
    targetPort: 3306
  selector:
    io.kompose.service: nextcloud-mariadb
