apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./kubernetes/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: nextcloud-mariadb
  name: nextcloud-mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nextcloud-mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./kubernetes/
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: nextcloud-mariadb
    spec:
      containers:
      - args:
        - --transaction-isolation=READ-COMMITTED
        - --binlog-format=ROW
        image: mariadb
        imagePullPolicy: ""
        name: nextcloud-mariadb
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: nextcloud-mariadb
        env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: nextcloud-secrets
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nextcloud-secrets
                key: MYSQL_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: nextcloud-secrets
                key: MYSQL_DATABASE
          - name: MYSQL_RANDOM_ROOT_PASSWORD
            value: "1"
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: nextcloud-mariadb
        persistentVolumeClaim:
          claimName: nextcloud-mariadb
status: {}
