apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./kubernetes/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: nextcloud-s3
  name: nextcloud-s3
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nextcloud-s3
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./kubernetes/
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: nextcloud-s3
    spec:
      containers:
      - args:
        - --compat
        - server
        - /data
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: nextcloud-secrets
              key: S3_ACCESS_KEY
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: nextcloud-secrets
              key: S3_SECRET_KEY
        image: minio/minio
        imagePullPolicy: ""
        name: nextcloud-s3
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: nextcloud-s3data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: nextcloud-s3data
        persistentVolumeClaim:
          claimName: nextcloud-s3data
status: {}
