apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./kubernetes/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: nextcloud-s3watch
  name: nextcloud-s3watch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nextcloud-s3watch
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./kubernetes/
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: nextcloud-s3watch
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - image: nickistre/nextcloud-s3watch
        imagePullPolicy: Always
        name: nextcloud-s3watch
        resources: {}
        env:
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: nextcloud-secrets
                key: S3_ACCESS_KEY
          - name: S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: nextcloud-secrets
                key: S3_SECRET_KEY
          - name: S3_BUCKETNAME
            valueFrom:
              secretKeyRef:
                name: nextcloud-secrets
                key: S3_BUCKETNAME
          - name: S3_HOST
            valueFrom:
              secretKeyRef:
                name: nextcloud-secrets
                key: S3_HOST
          - name: S3_PORT
            valueFrom:
              secretKeyRef:
                name: nextcloud-secrets
                key: S3_PORT
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
