apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: nextcloud-s3
  name: nextcloud-s3
spec:
  type: ClusterIP
  ports:
  - name: "s3"
    port: 9000
    targetPort: 9000
  selector:
    io.kompose.service: nextcloud-s3
