apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./kubernetes/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: nextcloud-web
  name: nextcloud-web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nextcloud-web
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./kubernetes/
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: nextcloud-web
    spec:
      containers:
      - image: nickistre/nextcloud-web
        imagePullPolicy: ""
        name: nextcloud-web
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /var/www/html
          name: nextcloud
          readOnly: true
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: nextcloud
        persistentVolumeClaim:
          claimName: nextcloud
          readOnly: true
status: {}
