apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: nextcloud-redis
  name: nextcloud-redis
spec:
  type: ClusterIP
  ports:
    - name: "redis"
      port: 6379
      targetPort: 6379
  selector:
    io.kompose.service: nextcloud-redis